# Services for local development
services:
  postgresql:
    image: postgres:16.6
    environment:
      - POSTGRES_DB=proconnect_ep
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"

  # This MongoDB will be seeded with mock data at each restart
  mongo:
    image: mongo:5.0.23
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fc_admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_API_USERNAME=fc
      - MONGO_INITDB_API_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/init:ro
      - ./docker/ssl:/etc/ssl:ro
    entrypoint: ["/init/entrypoint.sh"]
    tmpfs:
      - /data/db
      - /data/configdb

  pcdbapi:
    build: ./pcdbapi
    environment:
      - MONGODB_URL=mongodb://mongo:27017/core-fca-low?authSource=core-fca-low&directConnection=true
      - MONGODB_USERNAME=fc
      - MONGODB_PASSWORD=pass
      - MONGODB_CERTIFICATE_FILEPATH=/etc/ssl/mongo.pem
      - MONGODB_CA_FILEPATH=/etc/ssl/docker-stack-ca.crt
      - API_SECRET=pcdb-api-secret-key
      - CANT_RUN_TESTS=1
    ports:
      - "8000:8000"
    volumes:
      - ./pcdbapi:/app
      - ./docker/ssl:/etc/ssl:ro
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  pcdbapi-test:
    build:
      context: ./pcdbapi
      dockerfile: Dockerfile.test
    pull_policy: build
    profiles: ["test"]
    volumes:
      - ./pcdbapi:/app
      - ./docker/ssl:/etc/ssl:ro
    environment:
      - MONGODB_URL=mongodb://mongo:27017/proconnect_test?authSource=admin&directConnection=true
      - MONGODB_USERNAME=fc_admin
      - MONGODB_PASSWORD=pass
      - MONGODB_CERTIFICATE_FILEPATH=/etc/ssl/mongo.pem
      - MONGODB_CA_FILEPATH=/etc/ssl/docker-stack-ca.crt
      - API_SECRET=pcdb-api-secret-key
    depends_on:
      - mongo

  mailcatcher:
    image: maildev/maildev:2.2.1
    ports:
      - "1081:1080"
      - "1025:1025"
