# Services for local development
services:
  postgresql:
    image: postgres:16.6
    environment:
      - POSTGRES_DB=proconnect_ep
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      interval: 1s
      timeout: 2s
      test:
        - CMD-SHELL
        - pg_isready --dbname proconnect_ep --username usr
    ports:
      - "5432:5432"

  # This MongoDB will be seeded with mock data at each restart
  mongo:
    image: mongo:5.0.23
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fc_admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_API_USERNAME=fc
      - MONGO_INITDB_API_PASSWORD=pass
    healthcheck:
      interval: 1s
      timeout: 2s
      test:
        - CMD-SHELL
        - echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --tls --tlsAllowInvalidCertificates --username fc_admin --password pass --authenticationDatabase admin --quiet

    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/init:ro
      - ./docker/ssl:/etc/ssl:ro
    entrypoint: ["/init/entrypoint.sh"]
    tmpfs:
      - /data/db
      - /data/configdb

  pcdbapi:
    image: ghcr.io/proconnect-gouv/federation/api-partner@sha256:750172ac3fb8df2ff8447cb106a056e9b558d23c27029b207b2ea11301410c1a # latest
    environment:
      - MONGODB_URL=mongodb://mongo:27017/core-fca-low?authSource=core-fca-low&directConnection=true
      - MONGODB_USERNAME=fc
      - MONGODB_PASSWORD=pass
      - MONGODB_CERTIFICATE_FILEPATH=/etc/ssl/mongo.pem
      - MONGODB_CA_FILEPATH=/etc/ssl/docker-stack-ca.crt
      - API_SECRET=pcdb-api-secret-key
      - CLIENT_SECRET_CIPHER_PASS=test-pcdbapi-secret-cipher-passs
      - CANT_RUN_TESTS=1
    ports:
      - "8000:8000"
    volumes:
      - ./docker/ssl:/etc/ssl:ro
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'python -c "import urllib.request; urllib.request.urlopen(\"http://localhost:8000/healthz\")"'
      interval: 10s
      timeout: 5s
      retries: 5
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mailcatcher:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"
      - "1025:1025"
